import {state} from './model';
import {currentSky} from './observer-home';
import {skyTypeNames,skyDirection,satelliteSkyType,observerLook,type SkyType} from './observer-sky';
import {orbitDataset,orbitalRecord,orbitState,displayName} from './orbits';
import {escape,utcStamp} from './format';
import {icon,satelliteIcon} from './icons';
import './observer-home.css';
const action=(a:string,t:string,extra='',cls='ghost-button')=>`<button data-action="${a}" class="${cls}" ${extra}>${t}</button>`;
const shownSky=()=>currentSky()?.above.filter(s=>state.observerType==='all'||satelliteSkyType(s.record)===state.observerType)??[];
function locationControls(){const p=state.observerPosition;
 return `<div class="observer-location"><span class="observer-label">你在哪里</span><strong id="observer-position-label">${p?escape(p.label):'设置位置，看当地天空'}</strong>${p?`<p>${p.latitude.toFixed(4)}°，${p.longitude.toFixed(4)}°<br>${p.source==='browser'?`定位精度约 ${Math.round(p.accuracyMeters??0)} m`:'手动指定 · 不是设备定位'}${p.altitudeAssumed?' · 海拔按 0 m':''}</p>`:'<p>允许定位，或手动选择经纬度。位置只用于本页计算。</p>'}<div class="observer-location-actions">${action('observer-locate',state.observerStatus==='locating'?'正在定位…':p?'重新定位':'使用我的位置',state.observerStatus==='locating'?'disabled':'')}${p?action('observer-clear','清除位置','','tool-link'):''}</div><p class="observer-message" role="status">${escape(state.observerMessage)}</p><details id="observer-position-edit" data-detail><summary>手动设置位置 ${icon('chevron',14)}</summary><form id="observer-location-form"><label>纬度（北为正）<input name="latitude" type="number" min="-90" max="90" step="any" required value="${p?.latitude??''}" placeholder="如 39.90"></label><label>经度（东为正）<input name="longitude" type="number" min="-180" max="180" step="any" required value="${p?.longitude??''}" placeholder="如 116.40"></label><button type="submit" class="ghost-button">查看这个位置</button></form><div class="observer-city-presets">${[['北京',39.9042,116.4074],['上海',31.2304,121.4737],['旧金山',37.7749,-122.4194]].map(([name,lat,lon])=>action('observer-city',String(name),`data-lat="${lat}" data-lon="${lon}" data-label="${name}中心"`,'tool-link')).join('')}</div><p>城市按钮使用中心坐标；地形与建筑遮挡未计入。</p></details></div>`;
}
function emptySky(){const p=state.observerPosition,sky=currentSky();
 if(!p)return '<div class="observer-empty"><strong>先确定你的位置。</strong><p>取得位置后，才知道哪些卫星在你的地平线上方。当前未知，不表示没有卫星。</p></div>';
 if(!sky?.valid)return `<div class="observer-empty"><strong>轨道元素暂不可用于这个时刻。</strong><p>超出历元 ±72 小时或传播失败的对象不参与计算。请回到当前时间或刷新公开轨道。</p>${action('observer-live','回到当前时间')}${action('refresh-orbits','刷新公开轨道')}</div>`;
 return `<div class="observer-empty"><strong>${sky.above.length?'这个类型此刻没有凌空对象。':'当前目录中，此刻没有凌空卫星。'}</strong><p>名单只覆盖已接入的空间站、科学和气象卫星，不能推断全部在轨卫星都不在上空。</p></div>`;
}
function skyList(){const list=shownSky();return list.length?list.map(s=>`<button class="observer-satellite ${s.record.norad_id===state.activeNorad?'selected':''}" data-action="sky-select" data-norad="${s.record.norad_id}" aria-pressed="${s.record.norad_id===state.activeNorad}">${satelliteIcon(s.record.groups,20)}<span><strong>${escape(displayName(s.record))}</strong><small>${skyTypeNames[satelliteSkyType(s.record)]} · NORAD ${s.record.norad_id}</small></span><span class="observer-sat-look" data-look="${s.record.norad_id}">${skyDirection(s.azimuthDeg)} · 仰角 ${s.elevationDeg.toFixed(1)}°</span></button>`).join(''):emptySky();}
function selection(){const p=state.observerPosition,record=orbitalRecord(state.activeNorad),pv=record&&orbitState(record,state.orbitAt),look=p&&pv?observerLook(p,pv.position):null;
 if(!p||!record)return '<p class="observer-selection-empty">从右侧名单选择一颗，查看轨迹。</p>';
 return `<small>当前选中 · NORAD ${record.norad_id}</small><h2>${escape(displayName(record))}</h2><p id="observer-selected-look">${look?`${skyDirection(look.azimuthDeg)} · 仰角 ${look.elevationDeg.toFixed(1)}° · 距你 ${look.rangeKm.toFixed(0)} km${look.elevationDeg<=0?' · 已在地平线以下':''}`:'轨道元素在这个时刻不可用'}</p><div class="orbit-actions">${action('orbit-path',icon('orbit',17)+(state.layers.orbits?'隐藏轨迹':'显示轨迹'),`aria-pressed="${state.layers.orbits}" ${!pv?'disabled':''}`,'control-button')}${action('track',icon('focus',17)+(state.tracking?'退出跟随':'追踪这颗卫星'),`aria-pressed="${state.tracking}" ${!pv&&!state.tracking?'disabled':''}`,'control-button')}${action('orbit-source','轨道来源','','tool-link')}</div>`;
}
export function observerHomeView(){
 return `<section class="observer-home spatial-view" aria-label="此时此地的卫星"><div class="observer-home-local"><header class="observer-home-title"><div class="mission-label">HERE / NOW / ABOVE THE HORIZON</div><h1>此刻，抬头。</h1><p>以你的位置，看地平线上方的卫星。</p><div class="observer-now"><span id="observer-time-mode">${state.orbitLive?'实时 · 跟随现在':'时间推演 · 非此刻'}</span><time id="observer-local-time"></time><small id="observer-time-zone"></small></div></header>${locationControls()}<aside id="observer-selection" class="observer-selection" aria-label="选中卫星轨迹">${selection()}</aside></div><aside class="observer-sky-panel"><div class="observer-sky-heading"><div><small>当前公开目录中</small><h2>当地天空 <span id="observer-sky-count">—</span></h2></div>${action('observer-source',icon('info',17),'aria-label="凌空计算与覆盖范围"','icon-button')}</div><div class="observer-sky-types" role="group" aria-label="卫星类型">${(['all','stations','science','weather'] as SkyType[]).map(t=>action('sky-type',`${t==='all'?'全部':skyTypeNames[t]} <span id="observer-type-${t}">—</span>`,`data-type="${t}" aria-pressed="${state.observerType===t}"`,'observer-type')).join('')}</div><div id="observer-sky-list" class="observer-sky-list" aria-label="地平线上方的卫星名单">${skyList()}</div><p class="observer-sky-scope" id="observer-sky-scope"></p><p class="observer-sky-boundary">地平线上方 ≠ 肉眼可见。未计算日照、天气或建筑遮挡。</p>${action('navigate','查看完整卫星目录 '+icon('arrow',14),'data-view="satellites"','tool-link')}</aside><div class="network-camera">${action('home',icon('focus',18),'aria-label="回到我的位置"','control-button')}${action('zoom-in',icon('plus',18),'aria-label="放大地球"','control-button')}${action('zoom-out',icon('minus',18),'aria-label="缩小地球"','control-button')}<span>拖动旋转 · 双指缩放</span></div></section>`;
}
let listNode:HTMLElement|null=null,listKey='';
export function observerHomeReadouts(){
 if(!document.querySelector('.observer-home'))return;
 const sky=currentSky(),list=shownSky();
 const text=(id:string,value:string)=>{const n=document.getElementById(id);if(n)n.textContent=value;};
 text('observer-time-mode',state.orbitLive?'实时 · 跟随现在':'时间推演 · 非此刻');
 text('observer-local-time',new Date(state.orbitAt).toLocaleString('zh-CN',{hour12:false}));
 text('observer-time-zone',`设备时区 ${Intl.DateTimeFormat().resolvedOptions().timeZone} · ${utcStamp(state.orbitAt)}`);
 text('observer-sky-count',sky?String(sky.above.length):'—');
 for(const type of ['all','stations','science','weather'] as const)text('observer-type-'+type,sky?String(type==='all'?sky.above.length:sky.above.filter(s=>satelliteSkyType(s.record)===type).length):'—');
 text('observer-sky-scope',sky?`已计算 ${sky.valid} / ${orbitDataset.items.length} 个目录对象；${sky.unavailable} 个元素过期或不可计算。`:`目录 ${orbitDataset.items.length} 个对象 · 位置尚未提供`);
 const node=document.getElementById('observer-sky-list'),key=[list.map(s=>s.record.norad_id).join(','),state.activeNorad,state.observerType,!!state.observerPosition,sky?.valid].join('/');
 if(node&&(node!==listNode||key!==listKey)){
  const focus=document.activeElement as HTMLElement,focused=node.contains(focus)?focus.dataset.norad:undefined;node.innerHTML=skyList();listNode=node;listKey=key;if(focused)node.querySelector<HTMLElement>(`[data-norad="${focused}"]`)?.focus({preventScroll:true});
 }else for(const s of list){const n=node?.querySelector(`[data-look="${s.record.norad_id}"]`);if(n)n.textContent=`${skyDirection(s.azimuthDeg)} · 仰角 ${s.elevationDeg.toFixed(1)}°`;}
 const record=orbitalRecord(state.activeNorad),pv=record&&orbitState(record,state.orbitAt),p=state.observerPosition,look=p&&pv?observerLook(p,pv.position):null;
 text('observer-selected-look',look?`${skyDirection(look.azimuthDeg)} · 仰角 ${look.elevationDeg.toFixed(1)}° · 距你 ${look.rangeKm.toFixed(0)} km${look.elevationDeg<=0?' · 已在地平线以下':''}`:'轨道元素在这个时刻不可用');
 const selectionNode=document.getElementById('observer-selection');if(selectionNode)for(const control of selectionNode.querySelectorAll<HTMLButtonElement>('[data-action="orbit-path"],[data-action="track"]'))control.disabled=!pv&&!(control.dataset.action==='track'&&state.tracking);
 const play=document.querySelector<HTMLButtonElement>('.play-button');if(play){play.setAttribute('aria-label',state.orbitLive?'暂停实时':state.playing?'暂停':'播放');}
}
export function observerHomeSource(){return `<div class="dialog-heading"><div class="eyebrow">OBSERVER / TIME / LOCAL HORIZON</div><h2>怎样判断卫星此刻凌空？</h2><p>将有效轨道位置转换到你所在地的东方、北方和天顶方向；仰角大于 0°，才列入地平线上方名单。</p></div><dl class="spec-list"><div><dt>位置与权限</dt><dd>浏览器定位需你授权。没有授权时可手动设置。位置仅保留当前会话，不写入本地存储，不发送给应用API；不从IP猜测你的位置。手动城市坐标不是设备定位。</dd></div><div><dt>计算</dt><dd>现有 satellite.js 6.0.2 的WGS72/SGP4传播OMM，GMST近似地固坐标；以WGS84观察者计算方位角（北0°、东90°）、仰角与斜距（km）。未知海拔按0 m；定位精度不是轨道定位误差。</dd></div><div><dt>此时与推演</dt><dd>默认实时每秒跟随设备时钟。拖动时间或暂停后明确标为时间推演；回到当前时间恢复实时。显示设备时区与UTC，不由经度猜测当地法定时区。</dd></div><div><dt>数据覆盖</dt><dd>当前接入空间站、科学和气象卫星目录，并非全部在轨卫星。类型按来源分组，不宣称完整任务分类。超过轨道历元前后72小时或传播失败的对象不参与；零有效数据与零凌空对象分开。</dd></div><div><dt>不等于可见</dt><dd>只判断理想几何地平线。不含太阳照明、地影、天空亮度、天气、建筑、地形与大气折射；无法保证肉眼看见，也不是卫星遥测或实测定位。</dd></div></dl><a class="ghost-button" href="https://github.com/shashwatak/satellite-js" target="_blank" rel="noopener">satellite.js · 坐标与观察角 ${icon('external',14)}</a>`;}
