import {state} from './model';
import {orbitDataset, orbitalRecord, orbitState, matchRecords, displayName, groupNames} from './orbits';
import {escape, utcStamp} from './format';
import {icon,satelliteIcon} from './icons';

export function satelliteGroups() {
  const q = state.satelliteQuery.trim().toLowerCase();
  const matches = matchRecords(q, Object.keys(groupNames), state.favoritesOnly, state.favorites);
  let html = Object.entries(groupNames).map(([group, label]) => {
    const rows = matches.filter(r => r.groups.includes(group)); if (!rows.length) return '';
    const visible = state.visibleGroups.includes(group), collapsed = !q && state.collapsedGroups.includes(group);
    return `<section class="sat-group"><div class="sat-group-heading"><label title="在地球上显示这组卫星"><input type="checkbox" data-orbit-group="${group}" aria-label="显示${label}" ${visible ? 'checked' : ''}></label><button data-action="collapse-group" data-group="${group}" aria-expanded="${!collapsed}"><span class="group-type-icon">${satelliteIcon([group],16)}</span><span>${label}</span><span class="group-count">${rows.length}</span>${icon('chevron', 13)}</button></div><div class="sat-group-items" ${collapsed ? 'hidden' : ''}>${rows.map(r => {
      const valid = orbitState(r, state.orbitAt), favorite = state.favorites.includes(r.norad_id);
      return `<div class="public-sat-row ${r.norad_id === state.activeNorad ? 'selected' : ''} ${visible ? '' : 'group-hidden'}"><button class="sat-row-select" data-action="public-select" data-norad="${r.norad_id}" aria-label="选择 ${escape(displayName(r))}" aria-pressed="${r.norad_id === state.activeNorad}"><span class="sat-object-icon">${satelliteIcon(r.groups,20)}</span><span><strong>${escape(displayName(r))}</strong><small>NORAD ${r.norad_id} <em>${valid ? '轨道可用' : '超出有效窗口'}</em></small></span></button><button class="favorite-button ${favorite ? 'favorited' : ''}" data-action="favorite" data-norad="${r.norad_id}" aria-label="${favorite ? '取消收藏' : '收藏'} ${escape(displayName(r))}" aria-pressed="${favorite}">${icon('star', 15)}</button></div>`;
    }).join('')}</div></section>`;
  }).join('');
  if (!state.favoritesOnly && (!q || /天格|天宁|grid|55252|55261/.test(q))) html += `<section class="sat-group tiange-group"><div class="sat-group-heading"><button data-action="tiange-status"><span>天格候选编号</span><span class="group-count">2</span>${icon('info', 14)}</button></div><button class="tiange-status" data-action="tiange-status"><strong>当前没有可用公开轨道</strong><span>参考编号已再入 · 载荷身份待核实</span><small>55252 / 55261 · 查看目录证据 ${icon('external', 12)}</small></button></section>`;
  return html || `<div class="sat-empty">${icon('search', 28)}<strong>${state.favoritesOnly ? '还没有收藏卫星' : '没有匹配的卫星'}</strong><p>${state.favoritesOnly ? '点击卫星右侧的星标即可收藏。' : '试试名称、NORAD 编号或国际编号。'}</p><button class="text-button" data-action="clear-satellite-filter">显示全部卫星</button></div>`;
}
export function selectedOrbitDetails(context: 'scene' | 'catalog' = 'scene') {
  const record = orbitalRecord(state.activeNorad), pv = record && orbitState(record, state.orbitAt);
  if (!record) return '';
  return `<div class="selected-orbit"><div class="selected-orbit-heading"><span>当前选择</span><button data-action="orbit-source" aria-label="查看轨道来源">${icon('info', 15)} 来源</button></div><h2>${satelliteIcon(record.groups,21)}${escape(displayName(record))}</h2><div class="live-orbit-metrics"><div><span>高度</span><strong id="real-altitude">${pv ? pv.altitude.toFixed(1) : '—'}<small> km</small></strong></div><div><span>纬度</span><strong id="real-latitude">${pv ? pv.latitude.toFixed(2) : '—'}<small>°</small></strong></div><div><span>经度</span><strong id="real-longitude">${pv ? pv.longitude.toFixed(2) : '—'}<small>°</small></strong></div></div><p id="real-orbit-status">${pv ? 'SGP4 位置推算 · 非实时遥测' : '元素已超出 ±72 小时窗口，暂停位置展示。'}</p><button class="button subtle track-public" data-action="${context === 'catalog' ? 'locate-public' : 'track'}" ${pv ? '' : 'disabled'}>${icon('focus', 16)}${context === 'catalog' ? '在地球上查看' : state.tracking ? '退出跟随' : '跟随这颗卫星'}</button></div>`;
}
export function satellitePanel() {
  return `<aside class="satellite-panel" aria-label="卫星目录"><div class="sat-panel-header"><div><h2>卫星目录</h2><span>${orbitDataset.items.length} 个公开对象</span></div><button class="icon-button" data-action="refresh-orbits" aria-label="刷新公开轨道" title="刷新公开轨道">${icon('reset', 16)}</button></div><label class="satellite-search">${icon('search', 16)}<input id="satellite-search" type="search" value="${escape(state.satelliteQuery)}" placeholder="名称、NORAD 或国际编号" aria-label="搜索卫星"></label><div class="satellite-filter-tabs"><button data-action="satellite-filter" data-filter="all" class="${state.favoritesOnly ? '' : 'selected'}" aria-pressed="${!state.favoritesOnly}">全部卫星</button><button data-action="satellite-filter" data-filter="favorites" class="${state.favoritesOnly ? 'selected' : ''}" aria-pressed="${state.favoritesOnly}">${icon('star', 13)}已收藏 ${state.favorites.length}</button><button data-action="orbit-mode" data-mode="teaching">教学 A / B</button></div><div id="satellite-groups" class="satellite-groups">${satelliteGroups()}</div>${selectedOrbitDetails()}<div class="orbit-data-status" id="orbit-data-status">${escape(state.orbitStatus || 'CelesTrak OMM · 已载入来源快照')}</div></aside>`;
}
export function orbitSource() {
  const record = orbitalRecord(state.activeNorad)!;
  return `<div class="dialog-heading"><div class="eyebrow">PUBLIC ORBITAL ELEMENTS</div><h2>${satelliteIcon(record.groups,21)}${escape(displayName(record))}</h2><p>位置由真实公开轨道元素推算，不是卫星回传的实时定位。</p></div><dl class="spec-list"><div><dt>NORAD 编号</dt><dd>${record.norad_id}</dd></div><div><dt>国际编号</dt><dd>${escape(record.object_id)}</dd></div><div><dt>轨道历元</dt><dd>${utcStamp(record.epoch)}</dd></div><div><dt>实际取得时间</dt><dd>${utcStamp(record.captured_at)}</dd></div><div><dt>显示时刻</dt><dd>${utcStamp(state.orbitAt)}</dd></div><div><dt>来源格式</dt><dd>CelesTrak OMM / JSON</dd></div></dl><h3>计算与有效性</h3><p>使用 WGS72 / SGP4 传播至显示时刻；经 GMST 转换为近似地球固定坐标。地图经纬度是近似显示，不声称精密地球定向。超出历元前后72小时不显示位置。轨道元素每组至少间隔两小时刷新。</p><div class="source-links"><a href="${record.source_url}" target="_blank" rel="noopener">原始分组轨道 ${icon('external', 16)}</a><a href="https://celestrak.org/NORAD/elements/gp.php?CATNR=${record.norad_id}&FORMAT=JSON" target="_blank" rel="noopener">此卫星公开元素 ${icon('external', 16)}</a></div><p class="dialog-note">最新下载不等于最新历元；两者分别显示。教学实验使用独立 A/B 模型，不借用这颗卫星模拟真实探测。</p>`;
}
export function tiangeStatus() {
  return `<div class="dialog-heading"><div class="eyebrow">IDENTITY AND AVAILABILITY</div><h2>天格的轨道，为什么没有显示？</h2><p>参考材料给出了候选编号，但编号与载荷身份仍未核实。当前目录证据也表明这两个对象已经再入。</p></div>${orbitDataset.tiange_candidates.map(c => `<div class="candidate-record"><h3>NORAD ${c.norad_id} · ${escape(c.satcat.OBJECT_NAME)}</h3><p>目录再入日期：<strong>${escape(c.satcat.DECAY_DATE)}</strong>。当前 GP 端点返回 No GP data found。</p><a class="text-button" href="${c.source_url}" target="_blank" rel="noopener">查看 CelesTrak SATCAT 原始记录 ${icon('external', 15)}</a></div>`).join('')}<p class="dialog-note">这份证据解释候选编号的当前轨道不可用；不据此断言其载荷身份已确认。公开目录中的其他卫星可以正常选择、跟随和查看来源。</p>`;
}
