import {state} from './model';
import {modelAvailable} from './asset-availability';
import {orbitalRecord,displayName} from './orbits';
import {spacecraftModel,spacecraftModels} from './spacecraft';
import {icon,satelliteIcon} from './icons';
import {escape} from './format';
const button=(action:string,label:string,extra='',cls='tool-link')=>`<button class="${cls}" data-action="${action}" ${extra}>${label}</button>`;
export function satelliteModes(){return `<div class="satellite-modes" role="group" aria-label="卫星观察方式">${[['network','orbit','轨道追踪'],['structure','satellite','结构模型'],['catalog','objects','完整目录'],['payload','detector','载荷教学']].map(([page,glyph,label])=>button('satellite-page',icon(glyph,17)+label,`data-page="${page}" aria-pressed="${state.satellitePage===page}"`,state.satellitePage===page?'selected':'')).join('')}</div>`;}
export function structureStatus(){return state.structureLoad.startsWith('模型尚未公开')?escape(state.structureLoad):state.structureLoad.startsWith('正在')?'<i class="model-loading-mark" aria-hidden="true"></i>'+escape(state.structureLoad):'';}
export function structureView(){
  const model=spacecraftModel(),record=orbitalRecord(state.activeNorad),name=model?.name??(record?displayName(record):'所选卫星');
  return `<section class="structure-view spatial-view ${model?'':'structure-unavailable'}" aria-label="卫星结构模型">${satelliteModes()}<div class="structure-heading"><div class="mission-label">SPACECRAFT / NORAD ${state.activeNorad}</div><h1>${model?.norad===20580?'哈勃<span class="structure-name-break"><br></span>空间望远镜':escape(name)}</h1><div class="object-english">${model?'参考构型 · 非实时姿态':'MODEL NOT AVAILABLE'}</div><p>${model?.description??'这颗卫星的结构模型尚未接入。轨道资料可以继续查看，位置推算受元素有效期约束。'}</p>${button('satellite-page',`${icon('orbit',18)} 返回这颗卫星的轨道`,'data-page="network"','ghost-button')}${model?button('structure-source','模型数据与来源','','source-link'):''}</div>${model?`<details class="structure-anatomy" id="structure-learning" data-detail><summary>认识结构 ${icon('chevron',14)}</summary><div class="disclosure-body">${model.parts.map(([name,description],i)=>`<div><span>0${i+1}</span>${icon((model.norad===25544?['solar-array','truss','cabin']:['optics','solar-array','detector'])[i],30).replace('<svg','<svg class="anatomy-icon"')}<strong>${name}</strong><p>${description}</p></div>`).join('')}<p class="structure-note">${model.note}</p></div></details>`:`<div class="structure-empty">${satelliteIcon(record?.groups??[],72)}<strong>不以通用模型代替实物。</strong><p>你可以继续查看它的真实轨道，或选择已接入模型的航天器。</p></div>`}<div class="structure-switcher" role="group" aria-label="已接入的结构模型">${spacecraftModels.map(m=>button('structure-select',`${icon(m.norad===25544?'station':'telescope',22)}<span>${m.name}<small>NORAD ${m.norad}</small></span>`,`data-norad="${m.norad}" aria-pressed="${state.activeNorad===m.norad}"`,m.norad===state.activeNorad?'selected':'')).join('')}<span>${spacecraftModels.filter(m=>modelAvailable(m.file)).length} 个已公开模型 / 轨道目录独立</span></div><div class="structure-status" role="status">${structureStatus()}</div>${model?`<div class="structure-controls">${button('home',icon('focus',18),'aria-label="复位模型视角"','control-button')}${button('zoom-in',icon('plus',18),'aria-label="放大模型"','control-button')}${button('zoom-out',icon('minus',18),'aria-label="缩小模型"','control-button')}${button('structure-wire',icon('layers',17)+(state.structureWire?'实体材质':'结构网格'),`aria-pressed="${state.structureWire}"`,'control-button')}<span>拖动旋转 · 滚轮 / 双指缩放</span></div>`:''}</section>`;
}
export function structureSource(){const m=spacecraftModel();return `<div class="dialog-heading"><div class="eyebrow">SPACECRAFT MODEL PROVENANCE</div><h2>${m?.name??'所选卫星'} · 模型来源</h2></div><dl class="spec-list"><div><dt>对象身份</dt><dd>NORAD ${state.activeNorad}</dd></div><div><dt>模型署名</dt><dd>${m?.credit??'无已接入模型'}</dd></div><div><dt>形状与材质</dt><dd>原始 GLB 几何与纹理，居中归一化显示，保留部件比例。</dd></div><div><dt>展示边界</dt><dd>${m?.note??'没有用教学几何冒充此卫星。'}自由视角和演示照明不表示实时姿态；轨道点标记不按实物尺度放大。</dd></div></dl>${m?`<a class="ghost-button" href="${m.source}" target="_blank" rel="noopener">打开 NASA 原始模型 ${icon('external',16)}</a>`:''}`;}
